// <auto-generated />
using System;
using System.Collections.Generic;
using ChronoFlow.Server.Common.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChronoFlow.Server.Common.Persistence.Migrations
{
    [DbContext(typeof(ChronoFlowDbContext))]
    partial class ChronoFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Employees.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birthday");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_changed");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("personnel_number");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "ChronoFlow.Server.AccessManagement.Employees.Entities.Employee.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(25)
                                .HasColumnType("character varying(25)")
                                .HasColumnName("address_house_number");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("State")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_street");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "ChronoFlow.Server.AccessManagement.Employees.Entities.Employee.Name#EmployeeName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name_last_name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_access_management_employees");

                    b.HasIndex("PersonnelNumber")
                        .IsUnique();

                    b.ToTable("access_management_employees", (string)null);
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Employees.Entities.EmployeeEmail", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("fk_access_management_employee_emails")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeId", "Email")
                        .HasName("pk_access_management_employee_emails");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("fk_access_management_employee_emails");

                    b.ToTable("access_management_employee_emails", (string)null);
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Employees.Entities.EmployeePhoneNumber", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("fk_access_management_employee_phone_numbers")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeId", "PhoneNumber")
                        .HasName("pk_access_management_employee_phone_numbers");

                    b.HasIndex("fk_access_management_employee_phone_numbers");

                    b.ToTable("access_management_employee_phone_numbers", (string)null);
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Employees.Entities.EmployeeRole", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("EmployeeId", "RoleId")
                        .HasName("pk_access_management_employee_roles");

                    b.HasIndex("RoleId");

                    b.ToTable("access_management_employee_roles", (string)null);
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Permissions.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_access_management_permissions");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("access_management_permissions", (string)null);
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Roles.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_changed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_access_management_roles");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("access_management_roles", (string)null);
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Roles.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_access_management_role_permissions");

                    b.HasIndex("PermissionId");

                    b.ToTable("access_management_role_permissions", (string)null);
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Employees.Entities.EmployeeEmail", b =>
                {
                    b.HasOne("ChronoFlow.Server.AccessManagement.Employees.Entities.Employee", null)
                        .WithMany("Emails")
                        .HasForeignKey("fk_access_management_employee_emails")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Employees.Entities.EmployeePhoneNumber", b =>
                {
                    b.HasOne("ChronoFlow.Server.AccessManagement.Employees.Entities.Employee", null)
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("fk_access_management_employee_phone_numbers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Employees.Entities.EmployeeRole", b =>
                {
                    b.HasOne("ChronoFlow.Server.AccessManagement.Employees.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChronoFlow.Server.AccessManagement.Roles.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Roles.Entities.RolePermission", b =>
                {
                    b.HasOne("ChronoFlow.Server.AccessManagement.Permissions.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChronoFlow.Server.AccessManagement.Roles.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChronoFlow.Server.AccessManagement.Employees.Entities.Employee", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
