//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronoFlow.Client.Common.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChronoFlow.Client.Common.Localization.Resources.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Management.
        /// </summary>
        internal static string AccessManagement {
            get {
                return ResourceManager.GetString("AccessManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error occurred.
        /// </summary>
        internal static string AnUnhandledErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnhandledErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred: {0}.
        /// </summary>
        internal static string AnUnknownErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        internal static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed a day ago.
        /// </summary>
        internal static string ChangedADayAgo {
            get {
                return ResourceManager.GetString("ChangedADayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed a minute ago.
        /// </summary>
        internal static string ChangedAMinuteAgo {
            get {
                return ResourceManager.GetString("ChangedAMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed a month ago.
        /// </summary>
        internal static string ChangedAMonthAgo {
            get {
                return ResourceManager.GetString("ChangedAMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed an hour ago.
        /// </summary>
        internal static string ChangedAnHourAgo {
            get {
                return ResourceManager.GetString("ChangedAnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed a week ago.
        /// </summary>
        internal static string ChangedAWeekAgo {
            get {
                return ResourceManager.GetString("ChangedAWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed a year ago.
        /// </summary>
        internal static string ChangedAYearAgo {
            get {
                return ResourceManager.GetString("ChangedAYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed {0} days ago.
        /// </summary>
        internal static string ChangedDaysAgo {
            get {
                return ResourceManager.GetString("ChangedDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed {0} hours ago.
        /// </summary>
        internal static string ChangedHoursAgo {
            get {
                return ResourceManager.GetString("ChangedHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed just now.
        /// </summary>
        internal static string ChangedJustNow {
            get {
                return ResourceManager.GetString("ChangedJustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed {0} minutes ago.
        /// </summary>
        internal static string ChangedMinutesAgo {
            get {
                return ResourceManager.GetString("ChangedMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed {0} months ago.
        /// </summary>
        internal static string ChangedMonthsAgo {
            get {
                return ResourceManager.GetString("ChangedMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed {0} weeks ago.
        /// </summary>
        internal static string ChangedWeeksAgo {
            get {
                return ResourceManager.GetString("ChangedWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed {0} years ago.
        /// </summary>
        internal static string ChangedYearsAgo {
            get {
                return ResourceManager.GetString("ChangedYearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes were saved.
        /// </summary>
        internal static string ChangesSaved {
            get {
                return ResourceManager.GetString("ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock in.
        /// </summary>
        internal static string ClockIn {
            get {
                return ResourceManager.GetString("ClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a day ago.
        /// </summary>
        internal static string CreatedADayAgo {
            get {
                return ResourceManager.GetString("CreatedADayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a minute ago.
        /// </summary>
        internal static string CreatedAMinuteAgo {
            get {
                return ResourceManager.GetString("CreatedAMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a month ago.
        /// </summary>
        internal static string CreatedAMonthAgo {
            get {
                return ResourceManager.GetString("CreatedAMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created an hour ago.
        /// </summary>
        internal static string CreatedAnHourAgo {
            get {
                return ResourceManager.GetString("CreatedAnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a week ago.
        /// </summary>
        internal static string CreatedAWeekAgo {
            get {
                return ResourceManager.GetString("CreatedAWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created a year ago.
        /// </summary>
        internal static string CreatedAYearAgo {
            get {
                return ResourceManager.GetString("CreatedAYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} days ago.
        /// </summary>
        internal static string CreatedDaysAgo {
            get {
                return ResourceManager.GetString("CreatedDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} hours ago.
        /// </summary>
        internal static string CreatedHoursAgo {
            get {
                return ResourceManager.GetString("CreatedHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created just now.
        /// </summary>
        internal static string CreatedJustNow {
            get {
                return ResourceManager.GetString("CreatedJustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} minutes ago.
        /// </summary>
        internal static string CreatedMinutesAgo {
            get {
                return ResourceManager.GetString("CreatedMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} months ago.
        /// </summary>
        internal static string CreatedMonthsAgo {
            get {
                return ResourceManager.GetString("CreatedMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created: New to old.
        /// </summary>
        internal static string CreatedNewToOld {
            get {
                return ResourceManager.GetString("CreatedNewToOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created: Old to new.
        /// </summary>
        internal static string CreatedOldToNew {
            get {
                return ResourceManager.GetString("CreatedOldToNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} weeks ago.
        /// </summary>
        internal static string CreatedWeeksAgo {
            get {
                return ResourceManager.GetString("CreatedWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0} years ago.
        /// </summary>
        internal static string CreatedYearsAgo {
            get {
                return ResourceManager.GetString("CreatedYearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string EditingEntry {
            get {
                return ResourceManager.GetString("EditingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid e-mail address.
        /// </summary>
        internal static string EmailAddressValidationErrorMessage {
            get {
                return ResourceManager.GetString("EmailAddressValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry successfully deleted.
        /// </summary>
        internal static string EntryDeleted {
            get {
                return ResourceManager.GetString("EntryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry was not found.
        /// </summary>
        internal static string EntryNotFound {
            get {
                return ResourceManager.GetString("EntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry saved.
        /// </summary>
        internal static string EntrySaved {
            get {
                return ResourceManager.GetString("EntrySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid file extension.
        /// </summary>
        internal static string FileExtensionsValidationErrorMessage {
            get {
                return ResourceManager.GetString("FileExtensionsValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        internal static string IForgotMyPassword {
            get {
                return ResourceManager.GetString("IForgotMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Changed: Earlier to recent.
        /// </summary>
        internal static string LastChangedEarlierToRecent {
            get {
                return ResourceManager.GetString("LastChangedEarlierToRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Changed: Recent to earlier.
        /// </summary>
        internal static string LastChangedRecentToEarlier {
            get {
                return ResourceManager.GetString("LastChangedRecentToEarlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Data.
        /// </summary>
        internal static string MainData {
            get {
                return ResourceManager.GetString("MainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has a maximum length of {2} characters.
        /// </summary>
        internal static string MaxLengthValidationErrorMessage {
            get {
                return ResourceManager.GetString("MaxLengthValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has a minimum length of {2} characters.
        /// </summary>
        internal static string MinLengthValidationErrorMessage {
            get {
                return ResourceManager.GetString("MinLengthValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not permitted to delete the entry.
        /// </summary>
        internal static string MissingPermissionsToDeleteEntry {
            get {
                return ResourceManager.GetString("MissingPermissionsToDeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not permitted to view the list.
        /// </summary>
        internal static string MissingPermissionsToViewList {
            get {
                return ResourceManager.GetString("MissingPermissionsToViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: A - Z.
        /// </summary>
        internal static string NameAscending {
            get {
                return ResourceManager.GetString("NameAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Z - A.
        /// </summary>
        internal static string NameDescending {
            get {
                return ResourceManager.GetString("NameDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee.
        /// </summary>
        internal static string NewEmployee {
            get {
                return ResourceManager.GetString("NewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        internal static string NewRole {
            get {
                return ResourceManager.GetString("NewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        internal static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Number.
        /// </summary>
        internal static string PersonnelNumber {
            get {
                return ResourceManager.GetString("PersonnelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Number: A - Z.
        /// </summary>
        internal static string PersonnelNumberAscending {
            get {
                return ResourceManager.GetString("PersonnelNumberAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel Number: Z - A.
        /// </summary>
        internal static string PersonnelNumberDescending {
            get {
                return ResourceManager.GetString("PersonnelNumberDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has to be in range of {2} to {3}.
        /// </summary>
        internal static string RangeValidationErrorMessage {
            get {
                return ResourceManager.GetString("RangeValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is required.
        /// </summary>
        internal static string RequiredValidationErrorMessage {
            get {
                return ResourceManager.GetString("RequiredValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has to be {2} characters long.
        /// </summary>
        internal static string StringLengthValidationErrorMessage {
            get {
                return ResourceManager.GetString("StringLengthValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search.
        /// </summary>
        internal static string TypeToSearch {
            get {
                return ResourceManager.GetString("TypeToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid for an unknown reason.
        /// </summary>
        internal static string UnhandledValidationErrorMessage {
            get {
                return ResourceManager.GetString("UnhandledValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid URL.
        /// </summary>
        internal static string UrlValidationErrorMessage {
            get {
                return ResourceManager.GetString("UrlValidationErrorMessage", resourceCulture);
            }
        }
    }
}
